export const CREATE_SESSION = 'CREATE_SESSION';
export const REMOVE_SESSION = 'REMOVE_SESSION';
export const SESSIONLIST_CHANGED = 'SESSIONLIST_CHANGED';
export const SET_VOTE = 'SET_VOTE';
export const CLEAR_VOTES = 'CLEAR_VOTES';
export const USERS_CHANGED = 'USERS_CHANGED';
